let
    Source = Excel.Workbook(File.Contents("C:\Haritha\Files\Analysis_Invoices_Data\O365 historical data 2021_2022.xlsx"), null, true),
    #"Act 2021_2022 RU!SAPCrosstab1_DefinedName" = Source{[Item="Act 2021_2022 RU!SAPCrosstab1",Kind="DefinedName"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(#"Act 2021_2022 RU!SAPCrosstab1_DefinedName",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"Column38", type any}, {"Column39", type any}, {"Column40", type any}, {"Column41", type any}, {"Column42", type any}, {"Column43", type any}, {"Column44", type any}, {"Column45", type any}, {"Column46", type any}, {"Column47", type any}, {"Column48", type any}, {"Column49", type any}, {"Column50", type any}, {"Column51", type any}, {"Column52", type any}, {"Column53", type any}, {"Column54", type any}, {"Column55", type any}, {"Column56", type any}, {"Column57", type any}, {"Column58", type any}, {"Column59", type any}, {"Column60", type any}, {"Column61", type any}, {"Column62", type any}, {"Column63", type any}, {"Column64", type any}, {"Column65", type any}, {"Column66", type any}, {"Column67", type any}, {"Column68", type any}, {"Column69", type any}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,0,Replacer.ReplaceValue,{"Column7"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,0,Replacer.ReplaceValue,{"Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69"}),
    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value1",{"Column43", "Column44", "Column45", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69"}),
    #"Transposed Table" = Table.Transpose(#"Removed Columns"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Transposed Table",{{"Column1", type text}, {"Column2", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"Column1894"}),
    #"Merged Columns" = Table.CombineColumns(#"Removed Columns1",{"Column1", "Column2"},Combiner.CombineTextByDelimiter(",", QuoteStyle.None),"Date"),
    #"Merged Columns1" = Table.CombineColumns(#"Merged Columns",{"Date", "Column3"},Combiner.CombineTextByDelimiter(",", QuoteStyle.None),"Merged"),
    #"Merged Columns2" = Table.CombineColumns(#"Merged Columns1",{"Merged", "Column4"},Combiner.CombineTextByDelimiter(",", QuoteStyle.None),"MergedFinal"),
    #"Transposed Table1" = Table.Transpose(#"Merged Columns2"),
    #"Promoted Headers" = Table.PromoteHeaders(#"Transposed Table1", [PromoteAllScalars=true]),
    #"Changed Type2" = Table.TransformColumnTypes(#"Promoted Headers",{{",,,Customer", type text}, {",,,Material group", Int64.Type}, {",,,", type text}, {",,,Material", type text}, {",,,_1", type text}, {"Calendar Year,Period (month),,Customer industry", type text}, {"2021,1,Quantity,PCE", Int64.Type}, {"2021,1,Value,EUR", type number}, {"2021,1,avg. rate,EUR / PCE", type number}, {"2021,2,Quantity,PCE", Int64.Type}, {"2021,2,Value,EUR", type number}, {"2021,2,avg. rate,EUR / PCE", type number}, {"2021,3,Quantity,PCE", Int64.Type}, {"2021,3,Value,EUR", type number}, {"2021,3,avg. rate,EUR / PCE", type number}, {"2021,4,Quantity,PCE", Int64.Type}, {"2021,4,Value,EUR", type number}, {"2021,4,avg. rate,EUR / PCE", type number}, {"2021,5,Quantity,PCE", Int64.Type}, {"2021,5,Value,EUR", type number}, {"2021,5,avg. rate,EUR / PCE", type number}, {"2021,6,Quantity,PCE", Int64.Type}, {"2021,6,Value,EUR", type number}, {"2021,6,avg. rate,EUR / PCE", type number}, {"2021,7,Quantity,PCE", Int64.Type}, {"2021,7,Value,EUR", type number}, {"2021,7,avg. rate,EUR / PCE", type number}, {"2021,8,Quantity,PCE", Int64.Type}, {"2021,8,Value,EUR", type number}, {"2021,8,avg. rate,EUR / PCE", type number}, {"2021,9,Quantity,PCE", Int64.Type}, {"2021,9,Value,EUR", type number}, {"2021,9,avg. rate,EUR / PCE", type number}, {"2021,10,Quantity,PCE", Int64.Type}, {"2021,10,Value,EUR", type number}, {"2021,10,avg. rate,EUR / PCE", type number}, {"2021,11,Quantity,PCE", Int64.Type}, {"2021,11,Value,EUR", type number}, {"2021,11,avg. rate,EUR / PCE", type number}, {"2021,12,Quantity,PCE", Int64.Type}, {"2021,12,Value,EUR", type number}, {"2021,12,avg. rate,EUR / PCE", type number}, {"2022,1,Quantity,PCE", Int64.Type}, {"2022,1,Value,EUR", type number}, {"2022,1,avg. rate,EUR / PCE", type number}, {"2022,2,Quantity,PCE", Int64.Type}, {"2022,2,Value,EUR", type number}, {"2022,2,avg. rate,EUR / PCE", type number}, {"2022,3,Quantity,PCE", Int64.Type}, {"2022,3,Value,EUR", type number}, {"2022,3,avg. rate,EUR / PCE", type number}, {"2022,4,Quantity,PCE", Int64.Type}, {"2022,4,Value,EUR", type number}, {"2022,4,avg. rate,EUR / PCE", type number}, {"2022,5,Quantity,PCE", Int64.Type}, {"2022,5,Value,EUR", type number}, {"2022,5,avg. rate,EUR / PCE", type number}, {"2022,6,Quantity,PCE", Int64.Type}, {"2022,6,Value,EUR", type number}, {"2022,6,avg. rate,EUR / PCE", type number}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{",,,Customer", "Customer"}}),
    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Renamed Columns", {"Customer", ",,,Material group", ",,,", ",,,Material", ",,,_1", "Calendar Year,Period (month),,Customer industry"}, "Attribute", "Value"),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Unpivoted Columns", "Attribute", Splitter.SplitTextByDelimiter(",", QuoteStyle.None), {"Attribute.1", "Attribute.2", "Attribute.3", "Attribute.4"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Attribute.1", type text}, {"Attribute.2", type text}, {"Attribute.3", type text}, {"Attribute.4", type text}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type3",{{"Attribute.1", "Year"}, {"Attribute.2", "Month"}}),
    #"Merged Columns3" = Table.CombineColumns(#"Renamed Columns1",{"Attribute.3", "Attribute.4"},Combiner.CombineTextByDelimiter(":", QuoteStyle.None),"Merged"),
    #"Renamed Columns2" = Table.RenameColumns(#"Merged Columns3",{{"Calendar Year,Period (month),,Customer industry", "Customer industry"}, {",,,Material", "Material"}, {",,,Material group", "Material group"}}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Material group", type text}}),
    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type4",{{",,,_1", "Service"}, {",,,", "Service Group"}}),
    #"Pivoted Column" = Table.Pivot(#"Renamed Columns3", List.Distinct(#"Renamed Columns3"[Merged]), "Merged", "Value", List.Sum),
    #"Merged Columns4" = Table.CombineColumns(#"Pivoted Column",{"Year", "Month"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"Merged"),
    #"Changed Type5" = Table.TransformColumnTypes(#"Merged Columns4",{{"Merged", type date}}),
    #"Renamed Columns4" = Table.RenameColumns(#"Changed Type5",{{"Merged", "Date"}})
in
    #"Renamed Columns4"
