let
    Source = Excel.Workbook(File.Contents("C:\Haritha\Files\Analysis_Invoices_Data\Self Service Dashboard\OneDrive_2022-11-09\Packages Solutions_userfees_Charging_June22.xlsx"), null, true),
    rawdata_Sheet = Source{[Item="rawdata",Kind="Sheet"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(rawdata_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type any}, {"Column10", type text}, {"Column11", type text}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type any}, {"Column30", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type any}, {"Column34", type text}}),
    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Username", type text}, {"Country", type text}, {"Company name", type text}, {"Cost center", type text}, {"Company code", type text}, {"Email address", type text}, {"status", type text}, {"Roles", type text}, {"Costs", type number}, {"Service Type", type text}, {"Service", type text}, {"FDT debtor No", type text}, {"FTD Customer name", type text}, {"Month of invocing", type date}, {"Kabi Debtor no", type any}, {"Country_1", type text}, {"Kabi Debtor Name", type text}, {"CostCenter", type any}, {"Chargeable", type text}, {"Regional Allocation", type text}, {"Status AD", type text}, {"CC NAM", type text}, {"Charging CC", type text}, {"Company Code", type text}, {"Plant", type any}, {"Reporting Unit", type text}, {"Business", type text}, {"Invoice Text", type text}, {"GL Account", type text}, {"Company Name", type text}, {"PC", type text}, {"SAP System", type text}, {"Internal Order", type text}, {"comment", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Company Code", "Company Code.1"}, {"Company Name", "Company Name.1"}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Renamed Columns",{{"Cost center", "Avoid -Cost center"}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns1", "Kabi Debtor no", "Kabi Debtor no - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "Kabi Debtor Name", "Kabi Debtor Name - Copy"),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"Kabi Debtor no - Copy", type text}}, "en-US"),{"Kabi Debtor no - Copy", "Kabi Debtor Name - Copy"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"Merged"),
    #"Renamed Columns2" = Table.RenameColumns(#"Merged Columns",{{"Merged", "kabi debtor merged"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns2","FRESENIUS KABI AB","Fresenius Kabi AB",Replacer.ReplaceText,{"Kabi Debtor Name"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","186810-FRESENIUS KABI AB","186810-Fresenius Kabi AB",Replacer.ReplaceText,{"kabi debtor merged"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","FRESENIUS KABI S.A.","Fresenius Kabi S.A.",Replacer.ReplaceText,{"Kabi Debtor Name"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","391845-FRESENIUS KABI S.A.","391845-Fresenius Kabi S.A.",Replacer.ReplaceText,{"kabi debtor merged"}),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Replaced Value3", "Service", "Material code"),
    #"Replaced Value5" = Table.ReplaceValue(#"Duplicated Column2","eCTDmanager-Full Access & Unfinish Sequence","IT-000026",Replacer.ReplaceText,{"Material code"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value5","eCTDmanager-Full Access","IT-000027",Replacer.ReplaceText,{"Material code"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value4","eCTDmanager-View Access","IT-000028",Replacer.ReplaceText,{"Material code"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","EDMS-eDMS – QM Consumer","IT-000029",Replacer.ReplaceText,{"Material code"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","EDMS-eDMS – QM Contributor","IT-000030",Replacer.ReplaceText,{"Material code"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","EDMS-eDMS – R&D Contributor","IT-000031",Replacer.ReplaceText,{"Material code"}),
    #"Duplicated Column5" = Table.DuplicateColumn(#"Replaced Value9", "Material code", "Material code - Copy"),
    #"Duplicated Column3" = Table.DuplicateColumn(#"Duplicated Column5", "kabi debtor merged", "kabi debtor merged - Copy"),
    #"Reordered Columns" = Table.ReorderColumns(#"Duplicated Column3",{"Username", "Country", "Company name", "Avoid -Cost center", "Company code", "Email address", "status", "Roles", "Costs", "Service Type", "Service", "FDT debtor No", "FTD Customer name", "Month of invocing", "Kabi Debtor no", "Country_1", "Kabi Debtor Name", "CostCenter", "Chargeable", "Regional Allocation", "Status AD", "CC NAM", "Charging CC", "Company Code.1", "Plant", "Reporting Unit", "Business", "Invoice Text", "GL Account", "Company Name.1", "PC", "SAP System", "Internal Order", "Material code", "kabi debtor merged", "kabi debtor merged - Copy", "Material code - Copy"}),
    #"Merged Columns1" = Table.CombineColumns(#"Reordered Columns",{"kabi debtor merged - Copy", "Material code - Copy"},Combiner.CombineTextByDelimiter(":", QuoteStyle.None),"FinalMerged"),
    #"Changed Type2" = Table.TransformColumnTypes(#"Merged Columns1",{{"CostCenter", type text}}),
    #"Replaced Value19" = Table.ReplaceValue(#"Changed Type2","0000373108","373108",Replacer.ReplaceText,{"CostCenter"}),
    #"Duplicated Column4" = Table.DuplicateColumn(#"Replaced Value19", "CostCenter", "CostCenter - Copy"),
    #"Merged Columns2" = Table.CombineColumns(#"Duplicated Column4",{"FinalMerged", "CostCenter - Copy"},Combiner.CombineTextByDelimiter(":", QuoteStyle.None),"FinalMerged"),
    #"Appended Query" = Table.Combine({#"Merged Columns2", #"July : edms:Rawdata"}),
    #"Appended Query1" = Table.Combine({#"Appended Query", #"August : edms:Rawdata"}),
    #"Appended Query2" = Table.Combine({#"Appended Query1", #"September : edms:Rawdata-userlevel"}),
    #"Appended Query3" = Table.Combine({#"Appended Query2", #"October : edms:Rawdata (2)"}),
    #"Appended Query4" = Table.Combine({#"Appended Query3", #"May : edms:Rawdata"}),
    #"Appended Query5" = Table.Combine({#"Appended Query4", #"April : edms:Rawdata", #"March : edms:Rawdata", #"JanFeb : edms:Rawdata", #"November : edms:Rawdata"}),
    #"Duplicated Column6" = Table.DuplicateColumn(#"Appended Query5", "Month of invocing", "Month of invocing - Copy"),
    #"Renamed Columns3" = Table.RenameColumns(#"Duplicated Column6",{{"Month of invocing - Copy", "Billing Month"}}),
    #"Duplicated Column7" = Table.DuplicateColumn(#"Renamed Columns3", "Billing Month", "Billing Month - Copy"),
    #"Merged Columns3" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column7", {{"Billing Month - Copy", type text}}, "en-US"),{"FinalMerged", "Billing Month - Copy"},Combiner.CombineTextByDelimiter(":", QuoteStyle.None),"Merged"),
    #"Renamed Columns4" = Table.RenameColumns(#"Merged Columns3",{{"Merged", "FinalMerged"}}),
    #"Replaced Value10" = Table.ReplaceValue(#"Renamed Columns4","168406-Fresenius Kabi AB","168406-Fresenius Kabi AB - Denmark ",Replacer.ReplaceText,{"FinalMerged"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","FKD-Fresenius Kabi Deutschland GmbH-IT-000029:373108:","-Fresenius Kabi Deutschland GmbH - Egypt-IT-000029:373108:",Replacer.ReplaceText,{"FinalMerged"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","FKD-Fresenius Kabi Deutschland GmbH-IT-000031:373108:","-Fresenius Kabi Deutschland GmbH - Egypt-IT-000031:373108:",Replacer.ReplaceText,{"FinalMerged"}),
    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","FKD-Fresenius Kabi Deutschland GmbH-IT-000026:373108:","-Fresenius Kabi Deutschland GmbH - Egypt-IT-000026:373108:",Replacer.ReplaceText,{"FinalMerged"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","EDMS-QM Consumer","IT-000029",Replacer.ReplaceText,{"Material code"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","EDMS-QM Contributor","IT-000030",Replacer.ReplaceText,{"Material code"}),
    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","EDMS-R&D Contributor","IT-000031",Replacer.ReplaceText,{"Material code"}),
    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","eCTDmanager-Full Permissions","IT-000026",Replacer.ReplaceText,{"Material code"}),
    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","eCTDmanager-View Permissions","IT-000028",Replacer.ReplaceText,{"Material code"}),
    #"Filtered Rows" = Table.SelectRows(#"Replaced Value18", each ([Billing Month] <> null)),
    #"Changed Type3" = Table.TransformColumnTypes(#"Filtered Rows",{{"Business", type text}}),
    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type3", {"kabi debtor merged"}),
    #"Appended Query6" = Table.Combine({#"Removed Errors", #"NAM Raw data 01_05"})
in
    #"Appended Query6"
